### ISSUE TITLE
Better (a.k.a smalller) fake image generator

### ISSUE THREAD

**Issue by cyfra** [tensorflow/datasets#1361] opened 2020-01-09 15:39 UTC
Currently our fake_image code (get_random_picture) in fake_data_utils, is creating a truly random image (by randomizing each pixel).

This unfortunately means, that images are non-compresable, which results in large images in test_data directory.

The goal is to:
a) change that method to generate random images that compress better (for example maybe by generating larger 'tiles' instead of single pixels etc)
b) replacing the largest images that we have in our 'test_data' with more 'compressable' equivalents.

**Comment by Conchylicultor** [comment] 2020-01-09 18:04
Yes I completely agree. I had plan to add a script to parse all images in the `fake_data/` directory and replace all images by single colour of the same shape (Something like: `np.ones_like(original_image) * np.random.randint(max(original_image))`).

It shouldn't be too difficult, but the tricky part is that some images are compressed inside `.zip`, `.tar`,... archives. So ideally the script should also extract archives, replace images within the archive (without modifying other files) and recompress the archive with the right format.

I hadn't the time to add the script yet. If someone can help with this it would be great.

**Comment by Shashankjain12** [comment] 2020-01-12 19:21
Yes i will be happy to work on this issue @Conchylicultor  and @cyfra so if you won't mind can you assign me the issue so that I can work on that.!

**Comment by Shashankjain12** [comment] 2020-01-15 09:00
hey @Conchylicultor  and @cyfra can we use np.compress() method to compress those images?

**Comment by Shashankjain12** [comment] 2020-01-15 11:19
I got a bit confused in this case, To solve this problem I was thinking to use ```np.ones_like(original_image) * np.random.randint(np.amax(original_image))```
and for the compressing part I got a bit confused do we need to replace all the previously generated fake image files by it's compressed equivalant generated from above or just replace with newly generated fake files?

**Comment by Conchylicultor** [comment] 2020-01-15 18:20
The goal of the issue is to reduce the size of the `.png` and `.jpg` images present in the folder. `.png` and `jpg` images are format which already compress the image.

The issue is that white noise images by definition cannot be compressed, as they do not have any patterns and contains the maximum information. They are too random to be compressed by the png and jpg compression algorithm, so the resulting file has a big size.

You should not use np.compress. Instead, we want to replace all random images by uniform color images, which will have a much smaller size, as they contains very few information.

**Comment by Shashankjain12** [comment] 2020-01-15 19:04
So @Conchylicultor  i need to write the script which will iterate over all the archive files can be either ```.tar``` or ```.zip``` format  and then find ```.jpg``` or ```.png``` files and decompress them and replace them with their compressed equivalant images  and then recompress that folder containing images.

**Comment by Conchylicultor** [comment] 2020-01-15 20:05
That's correct. Note that images which are not already inside archives should be compressed as well. You may want to start by this as it may be easier.

For archives, I gave `zip` and `tar` as example, but they might be other format as well. For a list of archive format that we supports, have a look at: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/download/extractor.py#L189
You don't have too, but don't hesitate to reuse code from `extractor.py` if this helps.

**Comment by Shashankjain12** [comment] 2020-01-18 19:13
hello @Conchylicultor I had created the following script considering only  ```.zip``` file just for now. Kindly look at the script and give me suggestion whether it is alright or not or what do i need to change in the following:-
```
def compress(path):
    for subdir, dirs, files in os.walk(path):
        for file in files:
            filepath = subdir + os.sep + file
            if filepath.endswith(".jpeg") or filepath.endswith(".png"):
                img_arr=np.array(Image.open(filepath))
                img_arr=np.ones_like(img_arr) * np.random.randint(np.amax(img_arr))
                img=Image.fromarray(img_arr)
                img=img.convert("RGB")
                img.save(filepath)

def recompress(subdir,filepath,names):
    os.chdir(subdir)
    with zipfile.ZipFile(filepath,mode='w') as zf:
        for i in names: 
            zf.write(i)
            j=os.path.join(subdir,i)
            os.remove(j)
    
def extract(path):
    for subdir, dirs, files in os.walk(path):
        for file in files:
            filepath = subdir + os.sep + file
            if filepath.endswith(".zip"): 
                with zipfile.ZipFile(filepath,'r') as zip:
                    #print(filepath)
                    zip.extractall(path=subdir)
                    #print(filepath,zip.namelist())
                    compress(filepath)
                    
                os.remove(filepath)
                recompress(subdir,filepath,zip.namelist())

if __name__=='__main__':
    extract("/home/shashank/Desktop/gsoc_2020/datasets/tensorflow_datasets/testing")    
    compress("/home/shashank/Desktop/gsoc_2020/datasets/tensorflow_datasets/testing")
```

**Comment by Shashankjain12** [comment] 2020-01-18 19:14
I will do the path changes accordingly!!

**Comment by Conchylicultor** [comment] 2020-01-21 18:33
Thank you very much. This looks good, but I would refactor the code to make it more scalable to add more formats. How about something like:

```
def process_dir(path):
  for root, dirs, files in os.walk(path):
    for file in files:
      filepath = os.path.join(root, file)
      if is_image(filepath):
        rewrite_image(filepath)
      elif is_zip(filepath):
        rewrite_zip(filepath)
      elif is_tar(filepath):
        rewrite_tar(filepath)
      ...

def rewrite_zip(filepath):
  with tempfile.TemporaryDirectory() as tmpdirname:
    ... # Extract zip in tmpdirname
    process_dir(tmpdirname)  # Update images in the extracted zip
    ... # Compress the zip back into filepath
```

1. Only use a single `os.walk(path)` in a `process_dir`, and recursively call `process_dir`
1. Use `os.path.join` instead of `os.sep`
1. Extract the archive files in a new clear directory: `with tempfile.TemporaryDirectory() as tmpdirname:`. This way, you are guarantee there won't be any collision between filenames. And the directory get automatically deleted when exiting the contextmanager.
1. Add a `is_image(filename)` which also detect `.JPEG`, `.jpg`,... You can use `str.lower()` to help.

**Comment by Shashankjain12** [comment] 2020-01-21 20:10
Ok thanks for the suggestions @Conchylicultor  i will make the changes accordingly and then add to the repository :+1:

**Comment by Conchylicultor** [comment] 2020-01-21 20:14
Another important thing is to make sure the archive are safe. By default archives are allowed to extract files outside of the default directory. To make sure that paths are safe, have a look at the `_normpath` function in `extractor.py`

```
def _normpath(path):
  path = os.path.normpath(path)
  if (path.startswith('.')
      or os.path.isabs(path)
      or path.endswith('~')
      or os.path.basename(path).startswith('.')):
    return None
  return path
```

**Comment by dhirensr** [comment] 2020-02-20 21:49
@Conchylicultor : if no one is working on it I can take a look at it, and you can assign to me then.
I wanted to participate for GSOC 2020 with tfds

**Comment by Conchylicultor** [comment] 2020-02-26 18:41
Hey, @Shashankjain12 any update on this ? If not don't hesitate to share what you started so someone else could take over.

**Comment by vinayvr11** [comment] 2020-03-03 12:56
@Conchylicultor : I used `np.ones_like(original_image) * np.random.randint(np.amax(original_image)) ` this method but this method removes all the data of image and convert that image into gray all the information loss.
![image](https://user-images.githubusercontent.com/43430992/75777707-71839c80-5d7c-11ea-96c7-0d413664efda.jpg)

**Comment by vinayvr11** [comment] 2020-03-03 13:02
can i use lossless method to compress images

**Comment by Conchylicultor** [comment] 2020-03-03 17:06
@vinayvr11, removing the image content is exactly the point of the issue. Those images are just fake data used to test dataset generation pipeline. The content does not matter so we want them to be as small as possible.

**Comment by vinayvr11** [comment] 2020-03-03 18:45
What about setting a threshold for height and width of image and reduce the images dimension to this threshold value using openCV.
like->
`import cv2 as cv
scale = 20 #This variable reduced image size by 80 percent
width = int(img.shape[1]*scale/100) #Scaling of the image width
height   = int(img.shape[0]*scale/100) #Scaling of the image height
dim = (width,height) 
img_resize = cv.resize(img,dim,interpolation=cv.INTER_AREA)`

[Colab Link](https://colab.research.google.com/drive/1k1nkinf_mQJLy330IU-7Z5_6P-p-dwJF)

**Comment by vinayvr11** [comment] 2020-03-03 18:50
ok thanks for your suggestion @Conchylicultor. What about setting a threshold for height and width of image and reduce the images dimension to that threshold value using openCV.
like->
`import cv2 as cv
scale = 20 #This variable reduced image size by 80 percent
width = int(img.shape[1]*scale/100) 
height   = int(img.shape[0]*scale/100) 
dim = (width,height) 
img_resize = cv.resize(img,dim,interpolation=cv.INTER_AREA)`

I made a programme for that so please have a look at this and suggest me if anything wrong in my programme.
[Colab Work Link](https://colab.research.google.com/drive/1k1nkinf_mQJLy330IU-7Z5_6P-p-dwJF)

**Comment by Conchylicultor** [comment] 2020-03-03 19:07
@vinayvr11, can you give more context why you want to compress images rather than using the gray-scale as suggested ?
It it important that images keep the same shape, but content itself do not matter. The current images are already white noise, so do not contains any useful information.

**Comment by vinayvr11** [comment] 2020-03-03 20:34
I am sorry i think i need to understand the whole work first. So i have to make an parser which parse all the images and convert them into gray-scale as by the suggested method and after conversion recompress them into the same format from which those images will be extracted.

**Comment by Conchylicultor** [comment] 2020-03-03 22:55
@vinayvr11 This sounds correct. For coding, you can follow the structure proposed by my comment above: https://github.com/tensorflow/datasets/issues/1361#issuecomment-576818039

**Comment by vinayvr11** [comment] 2020-03-04 05:47
Thanks for clarification  @Conchylicultor. Now i finish this task today.

**Comment by vinayvr11** [comment] 2020-03-04 19:42
Hello @Conchylicultor  i have created the following script considering all archive files formats. And also tested the script on some test files and it works for every format. Kindly check the script and suggest me if there is anything left.
[Colab Link](https://colab.research.google.com/drive/1jkiw7tx7xTIc4qld87dZV8fjkketU6o4)
`def image_process(root,imgPath):
        for im in imgPath:
            if im.endswith('.jpeg') or im.endswith('.jpg') or im.endswith('.png'):
                img_path = os.path.join(root,im)
                image = np.array(Image.open(img_path))
                image = np.ones_like(image) * np.random.randint(np.amax(image))
                image = Image.fromarray(image)
                image = image.convert('RGB')
                image.save(img_path)  
    
        
def rewrite_zip(root,fileName):
    pathName = os.path.join(root,fileName.split('.')[0])

    if fileName.endswith('.zip'):
        files = []
        for _root, _directories, _files in os.walk(pathName):
            for filename in _files: 
                #join the two strings in order to form the full filepath. 
                filepath = os.path.join(_root, filename) 
                files.append(filepath)
            with ZipFile(root+fileName,'w') as zip:
                for file in files:
                    zip.write(file)
            shutil.rmtree(root+fileName.split('.')[0])
            
    elif fileName.endswith('.tar'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
        shutil.rmtree(root+fileName.split('.')[0])
    
    elif fileName.endswith('.tar.gz') or fileName.endswith('.tgz'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
        shutil.rmtree(root+fileName.split('.')[0])

    elif fileName.endswith('.tar.bz2'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
        shutil.rmtree(root+fileName.split('.')[0])      
  



def process_dir(path):
    
    for root,dirs,files in os.walk(path):
        
        for file in files:
            
            filepath = os.path.join(root,file)
            fileName = filepath.split('/')[-1]
            
            #For zip files
            if filepath.endswith('.zip'):
                with ZipFile(filepath,'r') as zip:
                    zip.extractall(path=root)
                    image_process(root,zip.namelist())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                    
                    
            #For tar.bz2 files
            elif filepath.endswith('tar.bz2'):
                with tarfile.open(filepath,'r:bz2') as tar:

                  tar.extractall()
                  image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                
                
            #For .tar files
            elif filepath.endswith('.tar'):
                with tarfile.open(filepath) as tar:

                  tar.extractall(root)
                  image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                
            
            #For .tar.gz files
            elif filepath.endswith("tar.gz") or filepath.endswith('.tgz'):
                with tarfile.open(filepath,'r:gz') as tar:
                  tar.extractall(path=root)
                  image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)`

**Comment by vinayvr11** [comment] 2020-03-04 19:44
Hello @Conchylicultor i have created the following script considering all archive files formats. And also tested the script on some test files and it works for every format. Kindly check the script and suggest me if there is anything left.
[Colab link](https://colab.research.google.com/drive/1jkiw7tx7xTIc4qld87dZV8fjkketU6o4)
`
def image_process(root,imgPath):
        for im in imgPath:
            if im.endswith('.jpeg') or im.endswith('.jpg') or im.endswith('.png'):
                 img_path = os.path.join(root,im)
                 image = np.array(Image.open(img_path))
                 image = np.ones_like(image) * np.random.randint(np.amax(image))
                 image = Image.fromarray(image)
                 image = image.convert('RGB')
                 image.save(img_path)  
    
        
def rewrite_zip(root,fileName):
    pathName = os.path.join(root,fileName.split('.')[0])

    if fileName.endswith('.zip'):
        files = []
        for _root, _directories, _files in os.walk(pathName):
            for filename in _files: 
                #join the two strings in order to form the full filepath. 
                filepath = os.path.join(_root, filename) 
                files.append(filepath)
            with ZipFile(root+fileName,'w') as zip:
                for file in files:
                    zip.write(file)
            shutil.rmtree(root+fileName.split('.')[0])
            
    elif fileName.endswith('.tar'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
        shutil.rmtree(root+fileName.split('.')[0])
    
    elif fileName.endswith('.tar.gz') or fileName.endswith('.tgz'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
        shutil.rmtree(root+fileName.split('.')[0])

    elif fileName.endswith('.tar.bz2'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
        shutil.rmtree(root+fileName.split('.')[0])      
  



def process_dir(path):
    
    for root,dirs,files in os.walk(path):
        
        for file in files:
            
            filepath = os.path.join(root,file)
            fileName = filepath.split('/')[-1]
            
            #For zip files
            if filepath.endswith('.zip'):
                with ZipFile(filepath,'r') as zip:
                    zip.extractall(path=root)
                    image_process(root,zip.namelist())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                    
                    
            #For tar.bz2 files
            elif filepath.endswith('tar.bz2'):
                with tarfile.open(filepath,'r:bz2') as tar:

                  tar.extractall()
                  image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                
                
            #For .tar files
            elif filepath.endswith('.tar'):
                with tarfile.open(filepath) as tar:

                  tar.extractall(root)
                  image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                
            
            #For .tar.gz files
            elif filepath.endswith("tar.gz") or filepath.endswith('.tgz'):
                with tarfile.open(filepath,'r:gz') as tar:
                  tar.extractall(path=root)
                  image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                  
                
           
            `

**Comment by vinayvr11** [comment] 2020-03-04 19:51
Hello @Conchylicultor i have created this script considering all the archive file formats and also tested this script on some test files. Kindly check the script and suggest me if i need to change something in it.

[Colab link](https://colab.research.google.com/drive/1jkiw7tx7xTIc4qld87dZV8fjkketU6o4)

`
def image_process(root,imgPath):
        print(root)
        for im in imgPath:
            if im.endswith('.jpeg') or im.endswith('.jpg') or im.endswith('.png'):
                img_path = os.path.join(root,im)
                image = np.array(Image.open(img_path))
                image = np.ones_like(image) * np.random.randint(np.amax(image))
                image = Image.fromarray(image)
                image = image.convert('RGB')
                image.save(img_path)
    
    
    
    
        
def rewrite_zip(root,fileName):
    pathName = os.path.join(root,fileName.split('.')[0])

    if fileName.endswith('.zip'):
        files = []
        for _root, _directories, _files in os.walk(pathName):
            for filename in _files: 
                #join the two strings in order to form the full filepath. 
                filepath = os.path.join(_root, filename) 
                files.append(filepath)
            with ZipFile(root+fileName,'w') as zip:
                for file in files:
                    zip.write(file)
            shutil.rmtree(root+fileName.split('.')[0])
            
    elif fileName.endswith('.tar'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
            shutil.rmtree(root+fileName.split('.')[0])
    
    elif fileName.endswith('.tar.gz') or fileName.endswith('.tgz'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
            shutil.rmtree(root+fileName.split('.')[0])

    elif fileName.endswith('.tar.bz2'):
        with tarfile.open(fileName, "w:gz") as tar_handle:
            for root, dirs, files in os.walk(pathName):
                for file in files:
                    tar_handle.add(os.path.join(root, file))
            shutil.rmtree(root+fileName.split('.')[0])      
  



def process_dir(path):
    
    for root,dirs,files in os.walk(path):
        
        for file in files:
            
            filepath = os.path.join(root,file)
            fileName = filepath.split('/')[-1]
            
            if filepath.endswith('.zip'):
                with ZipFile(filepath,'r') as zip:
                    zip.extractall(path=root)
                    image_process(root,zip.namelist())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                    
                    
                    
            elif filepath.endswith('tar.bz2'):
                with tarfile.open(filepath,'r:bz2') as tar:
                    tar.extractall()
                    image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                
                
            #For .tar file
            elif filepath.endswith('.tar'):
                with tarfile.open(filepath) as tar
                    tar.extractall(root)
                    image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                
            
            
            elif filepath.endswith("tar.gz") or filepath.endswith('.tgz'):
                with tarfile.open(filepath,'r:gz') as tar:
                    tar.extractall(path=root)
                    image_process(root,tar.getnames())
                os.remove(filepath)
                rewrite_zip(root,fileName)
                  `

**Comment by Conchylicultor** [comment] 2020-03-04 22:03
@vinayvr11 Thank you very much. This looks mostly good. Could you send a PR as it makes it easier for me to comment ?

Some remark:

* Please follow the style guide and pylint to format the code properly
* For the random generation, rather than pure randomness, we should make it deterministic such as running the script twice produce the same image. One way is to use the hash of the relative path % 255. As the relative path is constant across run, the images will be too.
* In my code snippet, I'm calling `process_dir` recursively inside `rewrite_zip`. This is better as it avoid the current code duplication that you have to check the file extension.
* Also, in my suggested script, the logic is more self-contained as all the zip-specific operations are self-contained inside the `_zip` function, rather than distributed among multiple function.

**Comment by vinayvr11** [comment] 2020-03-05 05:43
Sure first i make these changes in my code and then send you an PR of this to you. @Conchylicultor I have some doubt in the second point so first i explain you what i understand and then please correct me if i was wrong. So the random generation using `np.random.randint(np.amax(original_image))` this method won't works twice so i have to change that random generation with `Image_path%255` this method so that if the script runs twice we get the same results.

**Comment by vinayvr11** [comment] 2020-03-05 05:45
@Conchylicultor : Could you please assign this to me.

**Comment by vinayvr11** [comment] 2020-03-05 17:44
@Conchylicultor : here is my code with better version with all style guide follow. Now i want to know where did i suppose to add this code i mean in which script.
`# images_path variable to store the path of images for later compression
images_path = []


def image_process(root):
    """ Generate random images and remove noise of the
        images to compress better.

          Args:
           root: path of the images to get processed

    """
    images_path.append(root)
    image = np.array(Image.open(root))
    image = np.ones_like(image) * np.random.randint(np.amax(image))
    image = Image.fromarray(image)
    image = image.convert('RGB')
    image.save(root)


def rewrite_zip(filepath, filename):
    """ Rewrite the older .zip files into new better compressed one

            Args:
                filepath: path of the older zip file that need to be compressed
                filename: name of the older zip file that need to be compressed

    """
    # creating a temporary file to store images 
    temp = tempfile.TemporaryDirectory(dir=filepath)

    # Extraction of compressed .zip file
    with ZipFile(filepath+filename, 'r') as zip:
        zip.extractall(path=temp.name)
        print(temp.name)

        process_dir(temp.name+"/")  # Image Processing

    # Compressed the .zip file again
    with ZipFile(filepath+filename, 'w') as zip:
        for file in images_path:
            zip.write(file)


def rewrite_tar(filepath, filename):
    """ Rewrite the older .tar file into new better compressed one.
        Compression formats supports by this method (.tar.gz, .tgz, .tar.bz2)

            Args:
              filepath: path of the older .tar file that need to be compressed
              filename: name of the older .tar file that need to be compressed

    """
    # Create a tempfile to store the images with noise
    temp = tempfile.TemporaryDirectory(dir=filepath)

    # Extraction of .tar file
    with tarfile.open(filepath+filename, 'r') as tar:
        tar.extractall(path=temp.name)
        # Image Process to decrease the size
        process_dir(temp.name+"/")

    # Converting into tarfile again to decrease the space taken by the file-
    with tarfile.open(filepath+filename, 'w') as tar:
        for file in images_path:
            tar_handle.add(os.path.join(filepath, file))


def process_dir(path):
    """ This method process the whole directory which contains the
         compressed files.

          Args:
            path: path of the directory which contains all compression files

    """

    images_path = []
    for root, dirs, files in os.walk(path):
        for file in files:
            filepath = os.path.join(root, file)
            fileName = filepath.split('/')[-1]

            if filepath.endswith('.png') or filepath.endswith('.jpg')
            or filepath.endswith('.jpeg'):
                image_process(filepath)

            elif zipfile.is_zipfile(filepath):
                rewrite_zip(root, fileName)

            elif tarfile.is_tarfile(filepath):
                rewrite_tar(root, fileName)`

**Comment by Conchylicultor** [comment] 2020-03-18 01:01
Closing this as a first version has been created in https://github.com/tensorflow/datasets/pull/1661.

Will create a new issue with the remaining work to do.

**Closed by Conchylicultor** 2020-03-18 01:01 UTC
Labels: contributions welcome, enhancement, good first issue
