### ISSUE TITLE
AttributeError: module 'tensorflow_datasets' has no attribute 'ReadInstruction'

### ISSUE THREAD

**Issue by feapri** [tensorflow/datasets#1080] opened 2019-10-14 20:08 UTC
**Short description**
Description of the bug.
AttributeError: module 'tensorflow_datasets' has no attribute 'ReadInstruction'
when running the sample from https://github.com/tensorflow/datasets/blob/master/docs/splits.md:
"#or using the `ReadInstruction`:"
vals_ds = tfds.load('fashion_mnist:3.*.*', [
    tfds.ReadInstruction('train', from_=k, to=k+10, unit='%')
    for k in range(0, 100, 10)])

**Environment information**
* Operating System: Google's Colab
* Python version: Python 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: tfds tfds.__version__: 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tf.__version__: 2.0.0-rc2

**Reproduction instructions**
run the book (2 cells) on the link below in google's Colab
```
<put a code snippet or link to a gist here>
```
link to google's colab: 
https://drive.google.com/open?id=14mT3JSGJGGwh9bRCiVpZwPZ68n3fsb5V

link to nbviewer:
https://nbviewer.jupyter.org/github/feapri/tensorflow_practice/blob/master/errors/tf_ReadInstruction.ipynb

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
Update the documentation to reflect the proper attribute to be used

**Additional context**

**Comment by Conchylicultor** [comment] 2019-10-14 23:40
Thanks for reporting. Sorry about that. I though I had updated this. Sending a fix now (https://github.com/tensorflow/datasets/pull/1064).

Marking this as duplicate of: https://github.com/tensorflow/datasets/issues/1063

**Closed by Conchylicultor** 2019-10-14 23:40 UTC
Labels: bug, duplicate
