### ISSUE TITLE
Remove pieces of code that support python2

### ISSUE THREAD

**Issue by dhirensr** [tensorflow/datasets#1555] opened 2020-03-02 18:29 UTC
as we are dropping support for python2 as in https://github.com/tensorflow/datasets/issues/1552 and https://github.com/tensorflow/datasets/issues/1517 
there are few pieces of code which are written to support python2 only and can be reomved like https://github.com/tensorflow/datasets/blob/950309fec49d0b789878ba52d108362f354bd4a4/tensorflow_datasets/core/download/download_manager.py#L391

@Conchylicultor  if it's approved I can send a PR for the same.

**Comment by Conchylicultor** [comment] 2020-03-02 21:03
Sounds good to me, yes don't hesitate to send PR to cleanup the code.
I'm just marking this bug as duplicate of https://github.com/tensorflow/datasets/issues/1552 to have a single bug to track all Py2 cleanup.

**Closed by Conchylicultor** 2020-03-02 21:03 UTC
Labels: duplicate, enhancement
