### ISSUE TITLE
Trouble running tfds.exe on Windows 10

### ISSUE THREAD

**Issue by Chiafl** [tensorflow/datasets#3638] opened 2021-12-21 06:03 UTC
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\Scripts\tfds.exe\__main__.py", line 4, in <module>
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow_datasets\__init__.py", line 63, in <module>
    from tensorflow_datasets import vision_language
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow_datasets\vision_language\__init__.py", line 20, in <module>
    from tensorflow_datasets.vision_language.wit import Wit
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow_datasets\vision_language\wit\__init__.py", line 18, in <module>
    from tensorflow_datasets.vision_language.wit.wit import Wit
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow_datasets\vision_language\wit\wit.py", line 25, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
```

**Short description**
Having trouble building Custom Dataset with tfds.exe on Windows 10

**Environment information**
* Operating System: Windows 10
* Python version: 3.9.9
* `tensorflow-datasets`/`tfds-nightly` version: 4.4.0
* `tensorflow`/`tf-nightly` version: 2.7.0
* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes

**Reproduction instructions**
1. Install tensorflow_datasets
2. Run tfds.exe (by itself or any other command

**Additional context**
I am able to correctly create a custom dataset on windows subsystem for linux (ubuntu 20.04) but unable to do so on Windows platform following the same procedure.

**Comment by NUTSHELL-X** [comment] 2022-01-21 08:41
I encountered the problem just now and my environment is exactly same as yours with Window 10 , python 3.9.9 , tensorflow 2.7.0
Try install tensorflow-datasets instead of tfds-nightly.It works for me.

**Comment by Conchylicultor** [comment] 2022-01-31 11:20
Sorry for the trouble. Marking as duplicate of https://github.com/tensorflow/datasets/issues/3709.

We're in the process of releasing 4.5.1 version today. This should fix the issue

**Closed by Conchylicultor** 2022-01-31 11:20 UTC
Labels: bug
