### ISSUE TITLE
Can't load Reddit dataset following Overview instructions.

### ISSUE THREAD

**Issue by BenDavisson** [tensorflow/datasets#4920] opened 2023-05-18 19:22 UTC
I'm having an issue loading the 'reddit' dataset.   I've followed the instructions on the overview and can't get past [the loading step](https://www.tensorflow.org/datasets/overview#load_a_dataset).  

**What I've tried so far**
I am able to load the data for the `mnist` dataset... but it will not work for [the `reddit` dataset](https://www.tensorflow.org/datasets/catalog/reddit).  I get stuck on the same error displayed below.

**Stack Trace**
```
Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to C:\Users\benrd\tensorflow_datasets\reddit\1.0.0...
Extraction completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [38:38<00:00, 2318.01s/ file] 
Dl Size...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3141854161/3141854161 [38:38<00:00, 1355408.83 MiB/s] 
Dl Completed...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [38:38<00:00, 2318.01s/ url]
Traceback (most recent call last):
  File "C:\Users\benrd\Documents\Knauf-Dev\dash-chat\chat.py", line 52, in <module>
    ds = tfds.load('reddit', split='train', shuffle_files=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\wrapt\wrappers.py", line 578, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\logging\__init__.py", line 169, in __call__
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\load.py", line 640, in load
    _download_and_prepare_builder(dbuilder, download, download_and_prepare_kwargs)
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\load.py", line 499, in _download_and_prepare_builder
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\wrapt\wrappers.py", line 644, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\logging\__init__.py", line 169, in __call__
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 646, in download_and_prepare
    self._download_and_prepare(
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 1535, in _download_and_prepare
    future = split_builder.submit_split_generation(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\split_builder.py", line 341, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\core\split_builder.py", line 406, in _build_from_generator
    for key, example in utils.tqdm(
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\site-packages\tensorflow_datasets\datasets\reddit\reddit_dataset_builder.py", line 83, in _generate_examples
    d = json.loads(line)
        ^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benrd\anaconda3\envs\chatbot\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1385 (char 1384)
```

**Code**

```

import tensorflow as tf
import tensorflow_datasets as tfds

ds = tfds.load('reddit', split='train', shuffle_files=True)
assert isinstance(ds, tf.data.Dataset)
print(ds)
```

What could be causing this issue?  Thanks in advance.

**Comment by BenDavisson** [comment] 2023-05-24 15:55
@fineguy - I made a fresh environment with Conda and installed Tensorflow (v2.12.0) and Tensorflow Datasets(v4.9.2).  Here's a list of my entire environment:
```
(testTD) C:\Users\benrd\Documents\>conda list
# packages in environment at C:\Users\benrd\anaconda3\envs\testTD:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
array-record              0.2.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
etils                     1.3.0                    pypi_0    pypi
flatbuffers               23.5.9                   pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               2.18.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.59.0                   pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
jax                       0.4.10                   pypi_0    pypi
keras                     2.12.0                   pypi_0    pypi
libclang                  16.0.0                   pypi_0    pypi
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
ml-dtypes                 0.1.0                    pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   3.1.0                hcfcfb64_3    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
promise                   2.3                      pypi_0    pypi
protobuf                  4.23.1                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
python                    3.11.3          h2628c8c_0_cpython    conda-forge
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
tensorboard               2.12.3                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorflow                2.12.0                   pypi_0    pypi
tensorflow-datasets       4.9.2                    pypi_0    pypi
tensorflow-estimator      2.12.0                   pypi_0    pypi
tensorflow-intel          2.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
tensorflow-metadata       1.13.1                   pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.6.1                    pypi_0    pypi
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.16                  pypi_0    pypi
vc                        14.3                hb25d44b_16    conda-forge
vc14_runtime              14.34.31931         h5081d32_16    conda-forge
vs2015_runtime            14.34.31931         hed1258a_16    conda-forge
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.15.0                   pypi_0    pypi
```


I tried to run the same code listed above and received the same error:
`json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1385 (char 1384)`

I tried the command you suggested(`pip install --upgrade --force-reinstall tensorflow-datasets`) and received the following output:

```
(testTD) C:\Users\benrd\Documents\Knauf-Dev>pip install --upgrade --force-reinstall tensorflow-datasets
Collecting tensorflow-datasets
  Using cached tensorflow_datasets-4.9.2-py3-none-any.whl (5.4 MB)
Collecting absl-py (from tensorflow-datasets)
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting array-record (from tensorflow-datasets)
  Using cached array_record-0.2.0-py310-none-any.whl (3.0 MB)
Collecting click (from tensorflow-datasets)
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting dm-tree (from tensorflow-datasets)
  Using cached dm_tree-0.1.8-cp311-cp311-win_amd64.whl (101 kB)
Collecting etils[enp,epath]>=0.9.0 (from tensorflow-datasets)
  Using cached etils-1.3.0-py3-none-any.whl (126 kB)
Collecting numpy (from tensorflow-datasets)
  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
Collecting promise (from tensorflow-datasets)
  Using cached promise-2.3-py3-none-any.whl
Collecting protobuf>=3.20 (from tensorflow-datasets)
  Using cached protobuf-4.23.1-cp310-abi3-win_amd64.whl (422 kB)
Collecting psutil (from tensorflow-datasets)
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
Collecting requests>=2.19.0 (from tensorflow-datasets)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting tensorflow-metadata (from tensorflow-datasets)
  Using cached tensorflow_metadata-1.13.1-py3-none-any.whl (28 kB)
Collecting termcolor (from tensorflow-datasets)
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting toml (from tensorflow-datasets)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tqdm (from tensorflow-datasets)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting wrapt (from tensorflow-datasets)
  Downloading wrapt-1.15.0-cp311-cp311-win_amd64.whl (36 kB)
Collecting importlib_resources (from etils[enp,epath]>=0.9.0->tensorflow-datasets)
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting typing_extensions (from etils[enp,epath]>=0.9.0->tensorflow-datasets)
  Using cached typing_extensions-4.6.1-py3-none-any.whl (31 kB)
Collecting zipp (from etils[enp,epath]>=0.9.0->tensorflow-datasets)
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.19.0->tensorflow-datasets)
  Using cached charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl (96 kB)
Collecting idna<4,>=2.5 (from requests>=2.19.0->tensorflow-datasets)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.19.0->tensorflow-datasets)
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17 (from requests>=2.19.0->tensorflow-datasets)
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting colorama (from click->tensorflow-datasets)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting six (from promise->tensorflow-datasets)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting googleapis-common-protos<2,>=1.52.0 (from tensorflow-metadata->tensorflow-datasets)
  Using cached googleapis_common_protos-1.59.0-py2.py3-none-any.whl (223 kB)
Installing collected packages: dm-tree, zipp, wrapt, urllib3, typing_extensions, toml, termcolor, six, psutil, protobuf, numpy, importlib_resources, idna, etils, colorama, charset-normalizer, certifi, absl-py, tqdm, requests, promise, googleapis-common-protos, click, tensorflow-metadata, array-record, tensorflow-datasets
  Attempting uninstall: dm-tree
    Found existing installation: dm-tree 0.1.8
    Uninstalling dm-tree-0.1.8:
      Successfully uninstalled dm-tree-0.1.8
  Attempting uninstall: zipp
    Found existing installation: zipp 3.15.0
    Uninstalling zipp-3.15.0:
      Successfully uninstalled zipp-3.15.0
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.14.1
    Uninstalling wrapt-1.14.1:
      Successfully uninstalled wrapt-1.14.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.16
    Uninstalling urllib3-1.26.16:
      Successfully uninstalled urllib3-1.26.16
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.6.1
    Uninstalling typing_extensions-4.6.1:
      Successfully uninstalled typing_extensions-4.6.1
  Attempting uninstall: toml
    Found existing installation: toml 0.10.2
    Uninstalling toml-0.10.2:
      Successfully uninstalled toml-0.10.2
  Attempting uninstall: termcolor
    Found existing installation: termcolor 2.3.0
    Uninstalling termcolor-2.3.0:
      Successfully uninstalled termcolor-2.3.0
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.5
    Uninstalling psutil-5.9.5:
      Successfully uninstalled psutil-5.9.5
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.23.1
    Uninstalling protobuf-4.23.1:
      Successfully uninstalled protobuf-4.23.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
  Attempting uninstall: importlib_resources
    Found existing installation: importlib-resources 5.12.0
    Uninstalling importlib-resources-5.12.0:
      Successfully uninstalled importlib-resources-5.12.0
  Attempting uninstall: idna
    Found existing installation: idna 3.4
    Uninstalling idna-3.4:
      Successfully uninstalled idna-3.4
  Attempting uninstall: etils
    Found existing installation: etils 1.3.0
    Uninstalling etils-1.3.0:
      Successfully uninstalled etils-1.3.0
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.6
    Uninstalling colorama-0.4.6:
      Successfully uninstalled colorama-0.4.6
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.1.0
    Uninstalling charset-normalizer-3.1.0:
      Successfully uninstalled charset-normalizer-3.1.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2023.5.7
    Uninstalling certifi-2023.5.7:
      Successfully uninstalled certifi-2023.5.7
  Attempting uninstall: absl-py
    Found existing installation: absl-py 1.4.0
    Uninstalling absl-py-1.4.0:
      Successfully uninstalled absl-py-1.4.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.65.0
    Uninstalling tqdm-4.65.0:
      Successfully uninstalled tqdm-4.65.0
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: promise
    Found existing installation: promise 2.3
    Uninstalling promise-2.3:
      Successfully uninstalled promise-2.3
  Attempting uninstall: googleapis-common-protos
    Found existing installation: googleapis-common-protos 1.59.0
    Uninstalling googleapis-common-protos-1.59.0:
      Successfully uninstalled googleapis-common-protos-1.59.0
  Attempting uninstall: click
    Found existing installation: click 8.1.3
    Uninstalling click-8.1.3:
      Successfully uninstalled click-8.1.3
  Attempting uninstall: tensorflow-metadata
    Found existing installation: tensorflow-metadata 1.13.1
    Uninstalling tensorflow-metadata-1.13.1:
      Successfully uninstalled tensorflow-metadata-1.13.1
  Attempting uninstall: array-record
    Found existing installation: array-record 0.2.0
    Uninstalling array-record-0.2.0:
      Successfully uninstalled array-record-0.2.0
  Attempting uninstall: tensorflow-datasets
    Found existing installation: tensorflow-datasets 4.9.2
    Uninstalling tensorflow-datasets-4.9.2:
      Successfully uninstalled tensorflow-datasets-4.9.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-auth 2.18.1 requires urllib3<2.0, but you have urllib3 2.0.2 which is incompatible.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
tensorflow-intel 2.12.0 requires wrapt<1.15,>=1.11.0, but you have wrapt 1.15.0 which is incompatible.
Successfully installed absl-py-1.4.0 array-record-0.2.0 certifi-2023.5.7 charset-normalizer-3.1.0 click-8.1.3 colorama-0.4.6 dm-tree-0.1.8 etils-1.3.0 googleapis-common-protos-1.59.0 idna-3.4 importlib_resources-5.12.0 numpy-1.24.3 promise-2.3 protobuf-4.23.1 psutil-5.9.5 requests-2.31.0 six-1.16.0 tensorflow-datasets-4.9.2 tensorflow-metadata-1.13.1 termcolor-2.3.0 toml-0.10.2 tqdm-4.65.0 typing_extensions-4.6.1 urllib3-2.0.2 wrapt-1.15.0 zipp-3.15.0
```

**Comment by fineguy** [comment] 2023-06-28 12:05
@BenDavisson sorry for my delayed reply. Were you able to resolve the issue? If not, could you try using your system Python instead because I'm having problems reproducing your error?

**Comment by BenDavisson** [comment] 2023-06-29 13:04
I was not able to fix this issue.   Unfortunately, my use case requires that I can get this to run in an Anaconda environment.  

I did discover that the conda version of tensorflow-datasets is `4.8.3`... while the PyPI version is `4.9.2`.  Would this affect the ability for the reddit dataset to load?

**Comment by fineguy** [comment] 2023-07-14 06:41
I'm sorry that you still have this problem, but I'm closing this issue as there's not much I can do here.

**Closed by fineguy** 2023-07-14 06:41 UTC
Labels: help
