### ISSUE TITLE
TensorFlow - Having Trouble with Datasets

### ISSUE THREAD

**Issue by Moronixo** [tensorflow/datasets#3220] opened 2021-05-13 13:32 UTC
**What I need help with / What I was wondering**
I've been trying to load an image dataset I have stored locally for my TensorFlow project and I'm just not sure how to go around it, I've used https://www.tensorflow.org/datasets/add_dataset to help try to solve my issue but I'm a little confused on the details here. 

I'm running it on Python 3.8 in PyCharm, with Tensorflow 2.3.0.

Any help would be greatly appreciated

**Comment by Moronixo** [comment] 2021-05-13 16:47
The Dataset I'm trying to load is from here: https://www.kaggle.com/shyambhu/hands-and-palm-images-dataset

**Comment by NikhilBartwal** [comment] 2021-05-13 18:10
Hey @Moronixo, glad to know about you using TFDS!
We would be able to help you if you could clarify which part you are having trouble with. It would be even better if you could share the code that you are having problem with. Thanks !

**Comment by Moronixo** [comment] 2021-05-13 18:32
@NikhilBartwal Sorry for not clarifying it and thank you for helping me. I have this at the moment, which as far as I'm aware should download the dataset into .keras/datasets. But when I run the script, it comes back with a .tar file that's only 7kb big.
 
`dataset_url="https://www.kaggle.com/shyambhu/hands-and-palm-images-dataset/download"
data_dir = tf.keras.utils.get_file(origin=dataset_url,
                                   fname='hand_dataset',
                                   untar=True)
data_dir = pathlib.Path(data_dir)

**Comment by NikhilBartwal** [comment] 2021-05-14 18:39
Hey @Moronixo, the method that you are using is correct, however, it is not able to download the actual data as it is a Kaggle URl (Kaggle requires a person to signin first before downloading the data). That's why, the mehod is not working properly.

For accessing kaggle data, you can use `tfds.download.DownloadManager().download_kaggle_data()` as shown [here](https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager)

In the dataset name simply give `download_kaggle_data('shyambhu/hands-and-palm-images-dataset')`. This is download the zipped dataset in the specified directory. I hope this will clear your query. Thanks!

**Comment by Moronixo** [comment] 2021-05-16 15:48
@NikhilBartwal Really sorry if I'm missing something obvious here but when I use:
`tfds.download.DownloadManager(
    download_dir='C:/Users/oksej/.keras/datasets',
    dataset_name=download_kaggle_data(competition_or_dataset='shyambhu/hands-and-palm-images-dataset')
                              )`
It returns 
> TypeError: download_kaggle_data() missing 1 required positional argument: 'download_dir'

From reading the link you sent, I thought download_kaggle_data() only needed the competition_or_dataset value? How do I sort this issue?

**Comment by NikhilBartwal** [comment] 2021-05-16 15:56
Hey @Moronixo, the issue is stemming from the improper usage of `DownloadManager`. You can do something like this:
```
dl_manager = tfds.download.DownloadManager( download_dir='C:/Users/oksej/.keras/datasets')
dataset_path = dl_manager.download_kaggle_data(competition_or_dataset='shyambhu/hands-and-palm-images-dataset')
```

Since, the `download_kaggle_data()` is a method of the `DownloadManager` object. Hope this will clear your doubts. Thanks!

**Comment by Moronixo** [comment] 2021-05-16 16:35
@NikhilBartwal Sorry again, but I've done that and it's asked me to follow the installation of the Kaggle API and get the credentials, but after doing that it still doesn't work. 

I created the kaggle.json folder in ...appdata\roaming\python\python38\site-packages\kaggle and placed my .json file in containing my user credentials.

**Comment by NikhilBartwal** [comment] 2021-05-16 16:45
Hey @NikhilBartwal, First of all, you never need to apologize for asking your queries. We are a community, the more we help each other, the more we grow.

Regarding the issue, it seems that the Kaggle CLI was not installed properly. Please make sure that you have followed the steps s mentioned [here](url). If the issue still persists please provide the entire error so we can help more. Thanks!

**Comment by NikhilBartwal** [comment] 2021-05-16 16:48
The location to put the `.json` file appears to be `C:\Users\<USERNAME>\.kaggle\kaggle.json` on Windows system. You can have look at the link for other OSes.

**Comment by Moronixo** [comment] 2021-05-16 16:52
I'm on Windows 10, and I don't seem to have the .kaggle directory. I have uninstalled and reinstalled and it doesn't seem to appear.

**Comment by NikhilBartwal** [comment] 2021-05-16 16:56
Are you following the steps as mentioned in [here](https://www.kaggle.com/docs/api). Also, please share the full errors.

**Comment by Moronixo** [comment] 2021-05-16 17:02
Here is installing kaggle:
![image](https://user-images.githubusercontent.com/84026099/118405530-42e79e00-b670-11eb-8a22-c076de6c29bb.png)

Here are my user folders, showing no .kaggle folder:
![no kaggle](https://user-images.githubusercontent.com/84026099/118405556-74f90000-b670-11eb-9b91-5b0d8960af74.PNG)

And here is the full error I get:

2021-05-16 17:24:13.905700: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "C:\Users\oksej\anaconda3\envs\tf\lib\site-packages\tensorflow_datasets\core\download\kaggle.py", line 72, in _run_command
    return subprocess.check_output(command_args, encoding='UTF-8')
  File "C:\Users\oksej\anaconda3\envs\tf\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\oksej\anaconda3\envs\tf\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\oksej\anaconda3\envs\tf\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\oksej\anaconda3\envs\tf\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/oksej/PycharmProjects/pythonProject2/addDataset.py", line 20, in <module>
    dataset_path = dl_manager.download_kaggle_data(competition_or_dataset='shyambhu/hands-and-palm-images-dataset')
  File "C:\Users\oksej\anaconda3\envs\tf\lib\site-packages\tensorflow_datasets\core\download\download_manager.py", line 521, in download_kaggle_data
    return kaggle.download_kaggle_data(
  File "C:\Users\oksej\anaconda3\envs\tf\lib\site-packages\tensorflow_datasets\core\download\kaggle.py", line 149, in download_kaggle_data
    _download_competition_or_dataset(competition_or_dataset, tmp_data_dir)
  File "C:\Users\oksej\anaconda3\envs\tf\lib\site-packages\tensorflow_datasets\core\download\kaggle.py", line 103, in _download_competition_or_dataset
    _run_command([
  File "C:\Users\oksej\anaconda3\envs\tf\lib\site-packages\tensorflow_datasets\core\download\kaggle.py", line 82, in _run_command
    raise RuntimeError(textwrap.dedent("""\
RuntimeError: Error for command: kaggle datasets download --path C:\Users\oksej\.keras\datasets\shyambhu_hands-and-palm-images-dataset.incompleteXGR3IE shyambhu/hands-and-palm-images-dataset

To download Kaggle data through TFDS, follow the instructions to install
the kaggle API and get API credentials:
https://github.com/Kaggle/kaggle-api#installation

Additionally, you may have to join the competition through the Kaggle
website: https://www.kaggle.com/c/shyambhu/hands-and-palm-images-dataset

**Comment by NikhilBartwal** [comment] 2021-05-16 17:17
@Moronixo Have you tried creating a `.kaggle` folder yourself and putting the `.json` file in it?
Also, could you also confirm whether the `kaggle` command in working in `cmd`

**Comment by Moronixo** [comment] 2021-05-16 17:20
Creating the .kaggle folder worked. Thank you very much for your help, I really appreciate it!

**Comment by Moronixo** [comment] 2021-05-16 17:23
Just for clarification that it has been done I'll add an image of the extracted folder:
![clatification](https://user-images.githubusercontent.com/84026099/118406381-c0f97400-b673-11eb-813c-f83edafbc08b.PNG)

**Comment by NikhilBartwal** [comment] 2021-05-16 17:24
Great to know your doubt was cleared. Do let us know if you encounter any bugs in the future! 
I guess we can close this issue for now :)

**Closed** 2021-05-16 17:25 UTC
Labels: help
