### ISSUE TITLE
CelebA: Resource cannot infer ExtractMethod from filename

### ISSUE THREAD

**Issue by ericpts** [tensorflow/datasets#2321] opened 2020-08-19 09:40 UTC
**Short description**

When trying to load the CelebA dataset, the code fails with the error KeyError: <ExtractMethod.NO_EXTRACT: 1>, because the
`Resource()` constructor is unable to figure out the proper method from the filename.

**Environment information**
* Operating System: Debian Testing
* Python version: 3.8.5
* `tensorflow-datasets` version: '3.2.1'
* `tensorflow` version: 2.3.0

**Reproduction instructions**

```
python3 -m tensorflow_datasets.scripts.download_and_prepare --datasets=celeb_a
```

**Link to logs**
https://paste.ubuntu.com/p/K8BRHzp27d/

**Expected behavior**
The dataset should be properly loaded.

**Additional context**

This happens in `download_manager.py`, in the function `iter_archive`.
`resource` is `/home/ericpts/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pZjFTYXZWM3FlDDaXUAQO8EGH_a7VqGNLRtW52mva1LzDrb-V723OQN8`, and [Resource](https://www.tensorflow.org/datasets/api_docs/python/tfds/download/Resource) is unable to guess the ExtractMethod from the path.

If I manually specify it as `ExtractMethod.ZIP`, then everything works correctly.

**Comment by vijayphoenix** [comment] 2020-09-21 13:24
@ericpts 
We recently fixed a similar bug https://github.com/tensorflow/datasets/issues/2423. (Fixed by https://github.com/tensorflow/datasets/commit/bb2ce95481c401431ca922dd6e331a4b54def627)
This should appear in `tfds-nightly` soon.

Please try again and let us know the results.

**Comment by Conchylicultor** [comment] 2020-09-21 13:32
The CelebA bug is likely a duplicate of https://github.com/tensorflow/datasets/issues/1482

**Comment by zaccharieramzi** [comment] 2020-09-22 12:37
Hi @vijayphoenix ,

I tried just now with `tfds-nightly`, and still got the `KeyError: <ExtractMethod.NO_EXTRACT: 1>` error.
Do you know when the next nightly release will be?
It seems that it stopped on september 9th for some reason: https://pypi.org/project/tfds-nightly/#history .

**Comment by vijayphoenix** [comment] 2020-10-01 20:36
Hi @zaccharieramzi, 
Can you try again with updated `tfds-nightly`?

**Comment by oricou** [comment] 2020-10-02 15:46
I have just tried with version 3.2.1.dev202010020107, it still has the same issue

KeyError: <ExtractMethod.NO_EXTRACT: 1>

**Comment by tqa236** [comment] 2020-10-19 09:24
I just tried today with `tfds-nightly` (published on Docker Hub) and got the same error:

```
KeyError: <ExtractMethod.NO_EXTRACT: 1>
```

**Comment by sainivedh** [comment] 2020-10-24 09:26
celeba_bldr = tfds.builder('celeb_a')
celeba_bldr.download_and_prepare() 

Error:
KeyError: <ExtractMethod.NO_EXTRACT: 1>

**Comment by Conchylicultor** [comment] 2020-10-26 09:59
As explained above, the CelebA bug is likely a duplicate of #1482

**Comment by zaccharieramzi** [comment] 2020-11-02 14:05
Hi @vijayphoenix , I just retried with the latest nightly, and it gave the same error.

@Conchylicultor I have tried several times at different hours and I am not in China (and not using any VPN), so I guess the root cause for this issue is different than https://github.com/tensorflow/datasets/issues/1482 .

However, when inspecting the downloads, I indeed see an html file that looks like the following (with title `Google Drive - Quota exceeded`):

```
Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.
```

Maybe there is a problem related to this particular file for some reason.

Do you know how we can mitigate this issue by manually downloading the files ?
I see the drive links listed [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/celeba.py#L30), but I don't know then how to organise them in `~/tensorflow_datasets/celeb_a` or if I need to extract them.

**Comment by zaccharieramzi** [comment] 2020-11-02 14:31
Ok, I think I understood how the manual downloading should work.

Basically you can download all the files listed [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/celeba.py?rgh-link-date=2020-11-02T14%3A05%3A22Z#L30), put them in `~/tensorflow_datasets/downloads/manual/` and you can just run the `tfds.load('celeb_a'...` as normal. 
You can change the manually downloaded path with the [download config here](https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadConfig).

**Comment by vijayphoenix** [comment] 2020-12-29 14:58
Duplicate of https://github.com/tensorflow/datasets/issues/1482

You can also follow https://www.tensorflow.org/datasets/overview#troubleshooting for manual download

**Closed by vijayphoenix** 2020-12-29 14:58 UTC
Labels: bug

**Comment by liqinglin54951** [comment] 2021-01-28 19:49
KeyError: <ExtractMethod.NO_EXTRACT: 1> since your code need tfrecord files

**Comment by Ashvith** [comment] 2021-04-21 08:24
> celeb_a tfrecord files:
> https://drive.google.com/drive/folders/1MKQ9sRwr5OOFk3OBzLz91SsgF3MBqvtP?usp=sharing
> OR
> you can follow " Create tfrecord files for 'test', 'train', 'validation' " on cp13_Parallelizing NN Training w TF_printoptions(precision)_squeeze_shuffle_batch_repeat_image process_map_tfrecords (https://blog.csdn.net/Linli522362242/article/details/112386820)

Can this be done in Colab? I can't see the home directory....

**Comment by Ashvith** [comment] 2021-04-24 17:53
I think that this problem does not get fixed in Colab. I've tried in my laptop, and it works fine. But on Colab, nah, it just won't.
