### ISSUE TITLE
[load-data-error]: additional-pos-args-requested

### ISSUE THREAD

**Issue by saranshbh** [tensorflow/datasets#2196] opened 2020-07-14 18:17 UTC
**Error imported data from tfds**

**Environment information**
* Operating System: Windows 10
* Python version: 3.8
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets: 3.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow: 2.2.0

**Reproduction instructions**

```
(raw_train, raw_valid, raw_test), metadata = tfds.load(
    'cats_vs_dogs',
    split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
    with_info=True,
    as_supervised=True
)

```

**Error**
https://gist.github.com/saranshbh/7c5f9744d2ca3c9e9b88475e1b0c3d55

**Expected behavior**
Load the dataset. 

**Additional context**
Error is a TypeError expecting two positional arguments.

**Comment by vijayphoenix** [comment] 2020-07-14 20:27
We'll fix the issue soon but please downgrade to 3.1.0 in the meantime. This is a duplicate of #2190.

**Closed by vijayphoenix** 2020-07-14 20:27 UTC
Labels: bug
