### ISSUE TITLE
Download_and_prepare the300w_lp tensorflow

### ISSUE THREAD

**Issue by Rut-B** [tensorflow/datasets#1446] opened 2020-02-03 20:56 UTC
## The problem:
I try to get the300w_lp dataset of tensorflow. and I get this error:

### I try to run this code:
```
import tensorflow_datasets as tfds
import tensorflow as tf
im_300W_builder = tfds.builder('the300w_lp')
im_300W_builder.download_and_prepare()
```

### The error
> Downloading and preparing dataset the300w_lp (2.63 GiB) to /root/tensorflow_datasets/the300w_lp/1.0.0...
> Dl Completed...
> 1/|/100% 1/1 [00:00<00:00, 1.09 url/s]
> Dl Size...
> 0 MiB [00:00, ? MiB/s]
> Extraction completed...
> 0 file [00:00, ? file/s]
> /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> 
> ---------------------------------------------------------------------------
> NonMatchingChecksumError                  Traceback (most recent call last)
> <ipython-input-6-40698f58e7cb> in <module>()
> ----> 1 im_300W_builder.download_and_prepare()
>       2 
>       3 # Construct a tf.data.Dataset
>       4 # ds = im_300W_builder.as_dataset(split='train')
>       5 
> 
> 15 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/download_manager.py in _handle_download_result(self, resource, tmp_dir_path, sha256, dl_size)
>     214       self._record_sizes_checksums()
>     215     elif (dl_size, sha256) != self._sizes_checksums.get(resource.url, None):
> --> 216       raise NonMatchingChecksumError(resource.url, tmp_path)
>     217     download_path = self._get_final_dl_path(resource.url, sha256)
>     218     resource_lib.write_info_file(resource, download_path, self._dataset_name,
> 
> NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=0B7OEHD3T4eCkVGs0TkhUWFN6N1k, downloaded to /root/tensorflow_datasets/downloads/ucexport_download_id_0B7OEHD3T4eCkVGs0TkhUWFN6KF3egIz1jDXUd4a-SiFYeMLsQp-9ySO-6HOMfa9q4Bk.tmp.46234a79cb27432bb8c7c65c4bb6957d/uc, has wrong checksum.

this code work for me in the past, include today (3.2.20)
I try to run it in google colab, in some different computer, and with some different google account.
but the problem exist.

**Environment information**

* Operating System: google colab 
* Python version: python 3
* `tensorflow-datasets`/` version: 1.15.0

### how can I solve it?

Thanks

**Comment by Conchylicultor** [comment] 2020-02-19 19:52
Unfortunately, when too many users download the same drive file (or the same user download the same file multiple times), Google Drive will reject the download.

Created https://github.com/tensorflow/datasets/issues/1482 with some things to try. Closing this as duplicate of the new bug.

**Closed by Conchylicultor** 2020-02-19 19:52 UTC
Labels: help
