### ISSUE TITLE
Disable shuffling for tfds build

### ISSUE THREAD

**Issue by lely475** [tensorflow/datasets#2971] opened 2021-01-20 21:00 UTC
**What I need help with / What I was wondering**
I'm using the tfds cli to create a custom dataset for timeseries data. 
Everything is working as wanted and I can generate the data, however as all data is shuffled automatically it basically renders it useless for my task, as i need the timeseries data in correct order.

**It would be nice if...**
Is there any (easy) solution or workaround to disable shuffling when using tfds build?

**Environment information**
* Operating System: macOs BigSur
* Python version: 3.8
* `tfds-nightly` version: 4.1.0.dev202012100107
* `tensorflow` version: 2.4.0

**Comment by vijayphoenix** [comment] 2021-01-20 22:05
Afaik, `tfds build` does not shuffle the data.
Also, the shuffling by `tfds.load` is disabled by default.
https://www.tensorflow.org/datasets/api_docs/python/tfds/load

**Comment by lely475** [comment] 2021-01-21 08:39
So where I got the idea from is that when I used tfds-nightly 4.1.0.dev202012100107 it showed the following console output:

`Extraction completed...: 0 file [00:00, ? file/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]
Dl Completed...: 0 url [00:00, ? url/s]0%|                                      
**Shuffling and writing examples** to path/1.0.0.incompleteIZ30YN/ds-train.tfrecord   | 0/3 [00:00<?, ? splits/s]`

And I rechecked my `_generate_example` implementation, but couldn't find a fault with it so far.

**Comment by Conchylicultor** [comment] 2021-01-21 11:45
Yes, it would be nice in some cases, but it is currently tricky to do due to the TF-record files which are sharded, so when they are read, it is tricky to iterate in the proper order.

We are planning to migrate away of TF-record into a new format which would allow this.
In the meantime, I'm gonna mark this as duplicate of https://github.com/tensorflow/datasets/issues/113

**Closed by Conchylicultor** 2021-01-21 11:45 UTC
Labels: help

**Comment by lely475** [comment] 2021-01-21 12:22
Thank you for the info and referal to the issue #113, I was looking for a similar issue but hadn't found this one.

I assume the migration to a new format will still take a while? Is there any timeframe by which it might be done?
