### ISSUE TITLE
Kitti has bad checksum error on download

### ISSUE THREAD

**Issue by lmoroney** [tensorflow/datasets#1562] opened 2020-03-03 23:08 UTC
**Short description**
When using Kitti I get a bad checksum error when downloading the dataset

NonMatchingChecksumError: Artifact https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_object.zip, downloaded to /root/tensorflow_datasets/downloads/s3.eu-central-1_avg-kitti_devkit_objectLwMAO1uIjU-eBJEp605N-Wtd3-25ncIu5j-rD605uW0.zip.tmp.dbb0c85c8f604faf8f923efa33da7ad7/devkit_object.zip, has wrong checksum.

**Environment information**
* Operating System:  Google Colab
* Python version: Google Colab Version 3

**Reproduction instructions**
import tensorflow as tf
import tensorflow_datasets as tfds
data, info = tfds.load('kitti', with_info=True)
print(info)

** Logs **
---------------------------------------------------------------------------
NonMatchingChecksumError                  Traceback (most recent call last)
<ipython-input-12-d0473b53a795> in <module>()
      1 import tensorflow as tf
      2 import tensorflow_datasets as tfds
----> 3 data, info = tfds.load('kitti', with_info=True)
      4 print(info)
      5 #olddata, oldinfo = tfds.load('deep_weeds:1.0.0', with_info=True)

19 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/download_manager.py in _handle_download_result(self, resource, tmp_dir_path, sha256, dl_size)
    214       self._record_sizes_checksums()
    215     elif (dl_size, sha256) != self._sizes_checksums.get(resource.url, None):
--> 216       raise NonMatchingChecksumError(resource.url, tmp_path)
    217     download_path = self._get_final_dl_path(resource.url, sha256)
    218     resource_lib.write_info_file(resource, download_path, self._dataset_name,

NonMatchingChecksumError: Artifact https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_object.zip, downloaded to /root/tensorflow_datasets/downloads/s3.eu-central-1_avg-kitti_devkit_objectLwMAO1uIjU-eBJEp605N-Wtd3-25ncIu5j-rD605uW0.zip.tmp.dbb0c85c8f604faf8f923efa33da7ad7/devkit_object.zip, has wrong checksum.

**Expected behavior**
Kitti downloads and I see the info upon print_info

**Comment by Conchylicultor** [comment] 2020-03-03 23:20
This should have been fixed recently. Does the issue goes away with tfds-nightly ?

**Comment by Eshan-Agarwal** [comment] 2020-03-04 07:51
Actually I am also facing this error in patch_camelyon data-set. 

> NonMatchingChecksumError: Artifact https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz, downloaded to C:\Users\eshan\tensorflow_datasets\downloads\zeno.org_reco_2546_file_came_leve_2_spli_trbOY5E-X_2wontwSZI65F3fEMTim90H_hpA4Swq0obJw.gz.tmp.30bdbab3da2d4ca9be753a8b3df4cd84\camelyonpatch_level_2_split_train_x.h5.gz, has wrong checksum.

So I manually run again :
`python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=patch_camelyon `

And check checksum of `patch_camelyon .txt` and checksum for camelyonpatch_level_2_split_train_x.h5.gz always changes like for 1st run got checksum `https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz 2276258803 c3a2804354ef68cd755ab3409868047a0a60e62e9da87041831352e9f08c7fc7` and then it fails and give

`ExtractError: Error while extracting C:\Users\eshan\tensorflow_datasets\downloads\zeno.org_reco_2546_file_came_leve_2_spli_trS5fpbFu_uQ373HXQ7JgSTYVXiaCDa8XGyti2tU0HYwM.gz to C:\Users\eshan\tensorflow_datasets\downloads\extracted\GZIP.zeno.org_reco_2546_file_came_leve_2_spli_trS5fpbFu_uQ373HXQ7JgSTYVXiaCDa8XGyti2tU0HYwM.gz (file: ) : Compressed file ended before the end-of-stream marker was reached`

On 2nd run i got checksum : `https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz 2455485774 334d8b974b767d1f2f1195693dcfc06b379df7ac23156681d24012258646d022`
And again give error while downloading and extracting camelyonpatch_level_2_split_train_x.h5.gz

**Comment by vijayphoenix** [comment] 2020-03-04 08:47
Kitti checksum error fixed by https://github.com/tensorflow/datasets/pull/1507
Works with tfds-nightly.
See https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf

**Comment by Eshan-Agarwal** [comment] 2020-03-04 09:03
@vijayphoenix  Its working properly in colab either with tfds-nightly and tfds 2.1.0 but got extraction error when running locally 

Environment information

Operating System: Windows 10 (64bit)
Python version: 3.6.10
tfds version = 2.1.0
tensorflow version = 1.15.0

**Comment by vijayphoenix** [comment] 2020-03-04 09:09
Are you facing the extraction problem with the Kitti dataset or patch_camelyon dataset?
If the problem is related to patch_camelyon dataset, let's discuss it on issue https://github.com/tensorflow/datasets/issues/1551

**Comment by Eshan-Agarwal** [comment] 2020-03-04 09:15
@vijayphoenix  Got Extraction error for both Kitti dataset or patch_camelyon when running locally but on running on colab don't get.

**Comment by vijayphoenix** [comment] 2020-03-17 12:12
@lmoroney please close this issue if your problem goes tfds-nightly

**Comment by Conchylicultor** [comment] 2020-04-04 21:06
Closing this as tfds-nightly should have the new checksums.

**Closed by Conchylicultor** 2020-04-04 21:06 UTC
Labels: bug

**Comment by KamalLamichhane** [comment] 2020-07-24 10:14
NonMatchingChecksumError: Artifact http://vision.eng.shizuoka.ac.jp/csiq/dst_imgs.zip, downloaded to /root/tensorflow_datasets/downloads/vision.eng.shizuoka.ac.jp_csiq_dst_imgsX-ETcy6zbVXku6A1J7b7xRNgTdP0_qLW84MAch1ss5c.zip.tmp.35fcc42d978a43b3bd17b07d71899f6f/dst_imgs.zip, has wrong checksum.
