### ISSUE TITLE
Cannot download all datasets except mnist using command tfds.load().

### ISSUE THREAD

**Issue by Yisiheng** [tensorflow/datasets#807] opened 2019-07-24 07:14 UTC
**when I try to download the cifar10 using the below commands:
’‘’input:‘’‘
import tensorflow as tf
import tensorflow_datasets as tfds
data1=tfds.load('cifar10')

’‘’result:‘’‘
E0724 13:57:10.078672  1204 registered.py:171] Failed to construct dataset cifar10
Traceback (most recent call last):

  File "<ipython-input-15-157aebdffff9>", line 1, in <module>
    data1=tfds.load('cifar10')

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\registered.py", line 296, in load
    dbuilder = builder(name, data_dir=data_dir, **builder_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\registered.py", line 169, in builder
    return _DATASET_REGISTRY[name](**builder_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 188, in __init__
    self.info.initialize_from_bucket()

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 411, in initialize_from_bucket
    gcs_utils.download_gcs_file(fname, out_fname)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\utils\gcs_utils.py", line 40, in download_gcs_file
    resp = requests.get(url, stream=stream)

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)

ConnectionError: HTTPConnectionPool(host='storage.googleapis.com', port=80): Max retries exceeded with url: /tfds-data/dataset_info/cifar10/1.0.2/image.image.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F638AEDBE0>: Failed to establish a new connection: [WinError 10060] 。'))

‘’‘supplement’‘’：sometimes, 
**What I've amended source code, but I failed**
And when i use model tfds， i had closed the firewall.

**Environment information**
(if applicable)
* Operating System: Windows 10
* Python version: 3.7.3
* `tensorflow-datasets` version: 1.1.0
* `tensorflow` version: 1.13.1
* `Anaconda` version: 4.7.10

**Comment by us** [comment] 2019-07-24 11:31
gcs server refuses your connection. Did you send too many requests in short period of time? 

Try again in some time or change the ip and try again. 

If error still continue please report again.

**Comment by Yisiheng** [comment] 2019-07-24 14:56
> gcs server refuses your connection. Did you send too many requests in short period of time?
> 
> Try again in some time or change the ip and try again.
> 
> If error still continue please report again.

I didn’t sent too many requests in short period of time.
I wonder if that’s reason that the network link is unstable, because I’m in China.

**Comment by us** [comment] 2019-07-24 17:20
TFDS gave an error while retrieving `gcs_file` from `storage.googleapis.com`. The problem is not related to the `Cifar 10` dataset. TFDS retrieves some saved information about the dataset from the GCS.
Maybe China or your internet provider may have blocked access because of some special reasons. You can use a VPN to passing that problem.

**Comment by Yisiheng** [comment] 2019-07-25 00:38
> TFDS gave an error while retrieving `gcs_file` from `storage.googleapis.com`. The problem is not related to the `Cifar 10` dataset. TFDS retrieves some saved information about the dataset from the GCS.
> Maybe China or your internet provider may have blocked access because of some special reasons. You can use a VPN to passing that problem.

thank you for your resolution. I use a VPN ,then download dataset, error report follow,
'''input:'''
Data=tfds.load('cifar10')
'''result:'''
Downloading and preparing dataset cifar10 (162.17 MiB) to C:\Users\Administrator\tensorflow_datasets\cifar10\1.0.2...
HBox(children=(IntProgress(value=1, bar_style='info', description='Dl Completed...', max=1, style=ProgressStyl…
HBox(children=(IntProgress(value=1, bar_style='info', description='Dl Size...', max=1, style=ProgressStyle(des…
HBox(children=(IntProgress(value=1, bar_style='info', description='Extraction completed...', max=1, style=Prog…
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Traceback (most recent call last):

  File "<ipython-input-4-22d24cf56b1d>", line 1, in <module>
    Data=tfds.load('cifar10')

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\registered.py", line 299, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 287, in download_and_prepare
    download_config=download_config)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 948, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 804, in _download_and_prepare
    for split_generator in self._split_generators(dl_manager):

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\image\cifar.py", line 89, in _split_generators
    cifar_path = dl_manager.download_and_extract(self._cifar_info.url)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\download_manager.py", line 359, in download_and_extract
    return _map_promise(self._download_extract, url_or_urls)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\download_manager.py", line 395, in _map_promise
    res = utils.map_nested(_wait_on_promise, all_promises)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py", line 143, in map_nested
    return function(data_struct)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\download_manager.py", line 379, in _wait_on_promise
    return p.get()

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 510, in get
    return self._target_settled_value(_raise=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 514, in _target_settled_value
    return self._target()._settled_value(_raise)

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 224, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)

  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 842, in handle_future_result
    resolve(future.result())

  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()

  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception

  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\downloader.py", line 250, in _sync_download
    for block in iterator:

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)

ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')")', OSError("(10054, 'WSAECONNRESET')"))

**Comment by Conchylicultor** [comment] 2019-07-25 02:40
Yes, the GCS seems to be the issue. You can try to hack the code to disable the GCS

```
from tensorflow_datasets.core.utils import gcs_utils
gcs_utils.gcs_dataset_info_files = lambda *args, **kwargs: None
gcs_utils. is_dataset_on_gcs = lambda *args, **kwargs: False

tfds.load('cifar10')
```

Hopefully this should works. We should probably add an option so user can choose to disable GCS

**Comment by Yisiheng** [comment] 2019-07-25 05:41
> Yes, the GCS seems to be the issue. You can try to hack the code to disable the GCS
> 
> ```
> from tensorflow_datasets.core.utils import gcs_utils
> gcs_utils.gcs_dataset_info_files = lambda *args, **kwargs: None
> gcs_utils.is_dataset_on_gcs = lambda *args, **kwargs: False
> 
> tfds.load('cifar10')
> ```
> 
> Hopefully this should works. We should probably add an option so user can choose to disable GCS

emmmm,the way is impracticable.And I 

> Yes, the GCS seems to be the issue. You can try to hack the code to disable the GCS
> 
> ```
> from tensorflow_datasets.core.utils import gcs_utils
> gcs_utils.gcs_dataset_info_files = lambda *args, **kwargs: None
> gcs_utils.is_dataset_on_gcs = lambda *args, **kwargs: False
> 
> tfds.load('cifar10')
> ```
> 
> Hopefully this should works. We should probably add an option so user can choose to disable GCS

emmmm,the way is impracticable. I follow your instructions, but have still error. I'm mental breakdown.
'''
'''input:'''
from tensorflow_datasets.core.utils import gcs_utils
gcs_utils.gcs_dataset_info_files = lambda *args, **kwargs: None
gcs_utils.is_dataset_on_gcs = lambda *args, **kwargs: False

tfds.load('cifar10')
'''result:'''

Downloading and preparing dataset cifar10 (?? GiB) to C:\Users\Administrator\tensorflow_datasets\cifar10\1.0.2...
HBox(children=(IntProgress(value=1, bar_style='info', description='Dl Completed...', max=1, style=ProgressStyl…
HBox(children=(IntProgress(value=1, bar_style='info', description='Dl Size...', max=1, style=ProgressStyle(des…
HBox(children=(IntProgress(value=1, bar_style='info', description='Extraction completed...', max=1, style=Prog…
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Traceback (most recent call last):

  File "<ipython-input-3-a82cbfc9d7b8>", line 1, in <module>
    tfds.load('cifar10')

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\registered.py", line 299, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 287, in download_and_prepare
    download_config=download_config)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 948, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 804, in _download_and_prepare
    for split_generator in self._split_generators(dl_manager):

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\image\cifar.py", line 89, in _split_generators
    cifar_path = dl_manager.download_and_extract(self._cifar_info.url)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\download_manager.py", line 359, in download_and_extract
    return _map_promise(self._download_extract, url_or_urls)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\download_manager.py", line 395, in _map_promise
    res = utils.map_nested(_wait_on_promise, all_promises)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py", line 143, in map_nested
    return function(data_struct)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\download_manager.py", line 379, in _wait_on_promise
    return p.get()

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 510, in get
    return self._target_settled_value(_raise=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 514, in _target_settled_value
    return self._target()._settled_value(_raise)

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 224, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)

  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value

  File "C:\ProgramData\Anaconda3\lib\site-packages\promise\promise.py", line 842, in handle_future_result
    resolve(future.result())

  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()

  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception

  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_datasets\core\download\downloader.py", line 250, in _sync_download
    for block in iterator:

  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)

ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')")', OSError("(10054, 'WSAECONNRESET')"))
'''

**Comment by us** [comment] 2019-07-25 08:51
You closed the `gcs dataset info` files but you should give a path of downloaded dataset. 
``` data_dir: str (optional), directory to read/write data. Defaults datasets are stored.```

Usage:
`tfds.load('cifar10', data_dir='path/of/dataset')`

**Comment by Conchylicultor** [comment] 2019-07-25 15:33
It seems that you have an issue with your connection. `dl_manager.download_and_extract` fails because it does not find the file.
Can you access https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz without TFDS ?

**Comment by us** [comment] 2019-07-25 18:59
He can download `cifar10` directly, so I offered `data_dir` option. About `try_gcs`, I will send it because he get an error when downloading pre-processed file on GCS at the beginning. Isn't it same job with your offered code?
```from tensorflow_datasets.core.utils import gcs_utils
gcs_utils.gcs_dataset_info_files = lambda *args, **kwargs: None
gcs_utils.is_dataset_on_gcs = lambda *args, **kwargs: False

tfds.load('cifar10')```

**Comment by Yisiheng** [comment] 2019-07-26 09:25
@us the way also was unpractical, I guess that problem is caused by my connection. I try to connect by better vpn.
tfds.load('cifar10', data_dir='path/of/dataset', try_gcs=False)

**Comment by Yisiheng** [comment] 2019-07-26 09:29
@Conchylicultor  maybe, however I'm in China, the special issue feel unwell. I will try use better vpn to build connection.

**Comment by Conchylicultor** [comment] 2020-02-28 07:46
Closing this as the issue seems to be geo-restriction access. So not sure we can do anything from our end. Don't hesitate to post below is someone has a good solution.

**Closed by Conchylicultor** 2020-02-28 07:46 UTC
Labels: help

**Comment by JosFang** [comment] 2020-09-21 08:48
I guess the reason is that it is too slow to download this dataset

**Comment by xlcbingo1999** [comment] 2020-10-06 11:30
SAD. I have the same problem with you because we both live in CHINA!

**Comment by Conchylicultor** [comment] 2020-10-06 12:35
If you have issue with GCS, could you try set `_is_gcs_disabled = True` and report if this works ?
 https://github.com/tensorflow/datasets/blob/5dd79ad752cf87126eb70d8d267ce13526007829/tensorflow_datasets/core/utils/gcs_utils.py#L34

If so, could you try updating this function to catch the error which is raised, and skip GCS:

https://github.com/tensorflow/datasets/blob/5dd79ad752cf87126eb70d8d267ce13526007829/tensorflow_datasets/core/utils/gcs_utils.py#L43

**Comment by Conchylicultor** [comment] 2020-10-06 12:35
Also could you make sure the issue isn't already solved in `tfds-nightly` ?

**Comment by centrino13** [comment] 2021-02-16 16:36
I'm in China. Remember to set up the following configuration:
`import ssl
os.environ['http_proxy'] = 'http://127.0.0.1:12333'
os.environ['https_proxy'] = 'https://127.0.0.1:12333'
ssl._create_default_https_context = ssl._create_unverified_context`

`12333` is the number of port

**Comment by mo666666** [comment] 2023-02-17 15:23
I have the same issue. Are there any solutions for downloading CIFAR-10 manually? For example, download it through the Internet and upload it to **~/tensorflow_datasets/download/** directory.
