### ISSUE TITLE
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>

### ISSUE THREAD

**Issue by Nugine** [tensorflow/datasets#5355] opened 2024-04-06 15:06 UTC
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
Description of the bug.

**Environment information**
* Operating System: Ubuntu 22.04
* Python version: 3.10.12
* `tensorflow-datasets`/`tfds-nightly` version: `tfds-nightly 4.9.4.dev202404060044`
* `tensorflow`/`tf-nightly` version: `tensorflow 2.16.1`

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes.

**Reproduction instructions**

```python
import tensorflow_datasets as tfds

examples, metadata = tfds.load("ted_hrlr_translate/pt_to_en", with_info=True, as_supervised=True)
```

```bash
python3 a.py
```
```
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x71926a728940>
Traceback (most recent call last):
  File "/home/nugine/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
```

If you share a colab, make sure to update the permissions to share it.

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
What you expected to happen.

**Additional context**

**Comment by marcenacp** [comment] 2024-04-11 09:25
@Nugine I don't reproduce the issue on https://colab.sandbox.google.com.

Can you maybe try with `tensorflow==2.15`? We should adapt to the latest version of tf though.

**Comment by Nugine** [comment] 2024-04-11 10:53
I can reproduce in colab.
https://colab.research.google.com/drive/1OmXca6IkoirknPNyDGlxoG6U8w105SpE?usp=sharing

**Comment by wen020** [comment] 2024-04-12 14:23
I also encountered the same problem, is there any progress?

**Comment by marcenacp** [comment] 2024-04-17 07:08
> I can reproduce in colab. https://colab.research.google.com/drive/1OmXca6IkoirknPNyDGlxoG6U8w105SpE?usp=sharing

In this colab, you `pip install tfds-nightly` (tensorflow==2.16), can you instead use tensorflow==2.15? We're working on making TFDS fully compatible with the last version of TF.

Thanks!

**Comment by Nugine** [comment] 2024-04-17 07:47
tensorflow==2.15 has the same issue.

```
2024-04-17 07:45:47.987249: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-17 07:45:47.987331: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-17 07:45:47.989799: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-17 07:45:48.004805: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-17 07:45:49.531209: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
tf 2.15.0
tfds 4.9.4+nightly
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7965e32c6e60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
```

**Comment by marcenacp** [comment] 2024-04-17 11:40
@Nugine, can you share the full notebook? It works on https://colab.research.google.com/drive/1ZYxKQRONh259y6BzxfvVjlLHl-PK7S2B

**Comment by Nugine** [comment] 2024-04-17 11:58
> @Nugine, can you share the full notebook? It works on https://colab.research.google.com/drive/1ZYxKQRONh259y6BzxfvVjlLHl-PK7S2B

The error occurs when python process exits. You won't see it in jupyter environment.

https://colab.research.google.com/drive/1OmXca6IkoirknPNyDGlxoG6U8w105SpE?usp=sharing

![2024-04-17_19-56-31](https://github.com/tensorflow/datasets/assets/30099658/acb13936-1f56-47ad-a591-fa51243e4ce2)

**Comment by javierjuan** [comment] 2024-05-05 21:20
Is there any progress in getting a solution? I have the same problem

**Comment by congcongke** [comment] 2024-05-13 06:46
same problem for me

**Comment by marcenacp** [comment] 2024-05-13 11:28
I just re-opened the bug with the tensorflow team. The exception seems to be caught too late [in the code](https://github.com/tensorflow/tensorflow/blob/fd2a7a57c5276612faff2fa0bf4a908e48c73811/tensorflow/python/eager/polymorphic_function/atomic_function.py#L301-L311). Let's see what they say, thanks for your patience!

**Comment by WesleyHsieh0806** [comment] 2024-05-15 19:14
Same issue

**Comment by abdalhafid** [comment] 2024-05-21 10:49
same issue

**Comment by chengcongdu** [comment] 2024-05-30 03:02
+1

**Comment by ChaosAdmStudent** [comment] 2024-05-31 05:09
Following the same issue

**Comment by marcenacp** [comment] 2024-05-31 07:49
Update: the TensorFlow team is actively working on this issue. Thanks for your patience!

**Comment by Antoniodevy** [comment] 2024-06-05 12:17
Exception ignored in: <function AtomicFunction._del_ at 0x791a7d1a9c60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in _del_
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction._del_ at 0x791a7d1a9c60>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in _del_
TypeError: 'NoneType' object is not subscriptable can someone help

**Comment by livanosg** [comment] 2024-06-14 09:21
Problem still exists
```
Exception ignored in: <function AtomicFunction.__del__ at 0x7c7daba2ef20>
Traceback (most recent call last):
.../lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
Exception ignored in: <function AtomicFunction.__del__ at 0x7c7daba2ef20>
Traceback (most recent call last):
.../lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 0
```

**Comment by Haiyang-W** [comment] 2024-06-23 16:06
Any update? I also meet this problem.

**Comment by marcenacp** [comment] 2024-07-10 11:15
The issue is fixed in the newest versions:

```
!pip install -U tensorflow=="2.17.0rc1" tfds-nightly
```

Thanks everyone for your patience!

**Closed by marcenacp** 2024-07-10 11:15 UTC
Labels: bug

**Comment by Lucien1999s** [comment] 2024-07-11 07:39
> The issue is fixed in the newest versions:
> 
> ```
> !pip install -U tensorflow=="2.17.0rc1" tfds-nightly
> ```
> 
> Thanks everyone for your patience!

After I use this newest version, stopping here when I try training something... this code work in 2.16.0 version...:


See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["variety"] = encoder.fit_transform(y["variety"])
/opt/homebrew/Caskroom/miniconda/base/envs/deep-learning/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
Epoch 1/32

**Comment by Lucien1999s** [comment] 2024-07-14 08:04
After trying it, I found that as long as you don't specify the python environment of conda, and then use conda install tensorflow and tensorflow_datasets, it can run normally.

**Comment by alvaro-stylesage** [comment] 2024-07-18 12:54
Any way of solving it but keeping TF 2.15.* ?

**Comment by Orient-Dorey** [comment] 2024-09-09 13:03
> Any way of solving it but keeping TF 2.15.* ?

+1 on this question! :)
