### ISSUE TITLE
show_examples requires manual dict construction for some datasets

### ISSUE THREAD

**Issue by ntakouris** [tensorflow/datasets#2342] opened 2020-08-26 13:04 UTC
You can do:

`training_samples, ds_info = tfds.load('imagenette/320px', split='train', as_supervised=True, with_info=True)`

and 

`tfds.show_examples(ds_info, training_samples)` throws the following error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-59-b95a7afee814> in <module>()
----> 1 tfds.show_examples(ds_info, training_samples)

/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/visualization.py in show_examples(ds_info, ds, rows, cols, plot_scale, image_key)
    104           "tfds.show_examples requires examples as `dict`, with the same "
    105           "structure as `ds_info.features`. It is currently not compatible "
--> 106           "with `as_supervised=True`. Received: {}".format(type(ex)))
    107     ax = fig.add_subplot(rows, cols, i+1)
    108 

ValueError: tfds.show_examples requires examples as `dict`, with the same structure as `ds_info.features`. It is currently not compatible with `as_supervised=True`. Received: <class 'tuple'>
```

but 

`tfds.show_examples(ds_info, training_samples.map(lambda x, y: {'image': x, 'label': y}), image_key='image')` works. 

This is nowhere to be documented. I think it should be done automatically by tfds.

**Comment by Conchylicultor** [comment] 2020-08-26 14:48
This is because `show_examples` isn't compatible with `as_supervised` for now. This is a duplicate of https://github.com/tensorflow/datasets/issues/1575

Note: it seems you're using a very old TFDS version. I would suggest to upgrade it or use `!pip install tfds-nightly`.

`tfds.show_examples` argument order is now `(ds, ds_info)` for consistency with `tfds.load`

**Closed by Conchylicultor** 2020-08-26 14:48 UTC
Labels: documentation

**Comment by Conchylicultor** [comment] 2020-08-26 15:03
Note: I'm sending a fix now, it should appear in one the next tfds-nightly soon
