### ISSUE TITLE
duplicate logging message after calling tfds.load

### ISSUE THREAD

**Issue by SinaChavoshi** [tensorflow/datasets#2045] opened 2020-05-21 05:25 UTC
**Short description**
Description of the bug.
A call to tensorflow_datasets.load  adds an additional logging handler, tf registers a separate logging handler, this results in duplicate logging messages. 

example : 

**Environment information**
* Operating System: ubuntu 16
* Python version: 3.7
* `tensorflow-datasets` version: '2.0.0'
* `tensorflow` version:'2.1.0-dlenv_tfe'

**Reproduction instructions**

```
import tensorflow as tf
import tensorflow_datasets as tfds

(ds_train, ds_test), ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)

tf.get_logger().info('This info log will show up twice')
```

**Link to logs**
NA

**Expected behavior**
Only one log message should show up. 

**Additional context**
This behavior is described in details at https://stackoverflow.com/questions/6729268/log-messages-appearing-twice-with-python-logging

**Comment by Conchylicultor** [comment] 2020-05-21 15:41
I wasn't able to reproduce the issue. Could you share a colab which demonstrate the problem ?

**Comment by acharles7** [comment] 2020-06-18 18:53
Yes, I am able to reproduce this behavior. Here's colab notebook [logger.ipynb](https://colab.research.google.com/drive/1ILSvr56d2szUryxESLUac_Q5BFnEyKsI?usp=sharing)

**Comment by vijayphoenix** [comment] 2020-06-18 19:33
Adding this should fix the issue
```
tf.get_logger().propagate = False
```
For more info on why logging happens twice see https://github.com/tensorflow/tensorflow/issues/8023

Closing this issue because it is not related to tfds.
Feel free to reopen if you feel I'm mistaken.

**Closed by vijayphoenix** 2020-06-18 19:33 UTC
Labels: bug

**Comment by Conchylicultor** [comment] 2020-06-18 20:23
`tf.get_logger()` is deprecated I think. You should try to use `absl.logging` directly or `import logging`.
