### ISSUE TITLE
dl_manager extract multiple and nested files method

### ISSUE THREAD

**Issue by us** [tensorflow/datasets#251] opened 2019-03-14 18:39 UTC
**Feature request related to the below problem.**
dl_manager.download_and_extract method just extracted the downloaded file, not the files inside. 

**Describe the solution**
We can add a feature to dl_manager download extract all files recursively.

**Comment by Conchylicultor** [comment] 2019-03-19 16:15
I think this is the intended behavior. To extract recursively, the solution is to call `dl_manager.extract` multiple times:

```python
archive_path = dl_manager.download_and_extract('http://a.org/data.zip')
train_dir, test_dir = dl_manager.extract([
    os.path.join(archive_path, 'train.gz'),
    os.path.join(archive_path, 'test.gz'),
])
```

Closing this, don't hesitate to re-open if this does not solve your issue.

**Closed by Conchylicultor** 2019-03-19 16:15 UTC
Labels: enhancement
